# La base de NumPy - ndarray

Toda la libería de NumPy se articula alrededor de una única estructura de datos: la matriz multidimensional o ndarray (N-dimensional array).<br/>

### Características básicas de ndarray

<ul>
<li>Un ndarray puede contener elementos de <b>CUALQUIER TIPO</b></li>
<li>Todos los elementos de un ndarray deben tener <b>EL MISMO TIPO</b>.</li>
<li>El tamaño de un ndarray (número de elementos) se define en el momento de la creación y no puede modificarse.</li>
<li>Pero la organización de esos elementos entre diferentes dimensiones sí puede modificarse</li>
</ul>

### Uso básico de cualquier elemento de NumPy

Hay que recordar que NumPy no es un módulo del core de Python por lo que SIEMPRE habrá que importarlo de forma completa o componente a componente.

In [2]:
import numpy as np

### Creación básica de ndarrays

Existen varias formas de crear un ndarray en NumPy. Vamos a ver las más relevantes.

#### Creacion de un ndarray de vacio

In [5]:
# Especificando dimensiones
array_vacio = np.empty((3,2), dtype = np.unicode_)
array_vacio

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [6]:
# Copiando dimensiones y tipo desde otra estructura
array_vacio_copia = np.empty_like([1, 2, 3, 4, 5])
array_vacio_copia

array([                  0, 4602678819172646912, 4607182418800017408,
       4609434218613702656, 4611686018427387904])

#### Creacion de ndarray de unos

In [8]:
# Especificando dimensiones
array_unos = np.ones((3, 2))
array_unos

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
# Copiando dimensiones y tipo desde otra estructura
array_unos_copia = np.ones_like([1, 2, 3, 4, 5])
array_unos_copia

array([1, 1, 1, 1, 1])

#### Creacion de ndarray de ceros

In [10]:
# Especificando dimensiones
array_ceros = np.zeros((3, 2))
array_ceros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
# Especificando dimensiones y tipo desde otra estructura
array_ceros_copia = np.zeros_like([1, 2, 3, 4, 5])
array_ceros_copia

array([0, 0, 0, 0, 0])

#### Creacion de un ndarray con la matriz identidad

In [13]:
# Crea una matriz identidad de 3x3 con los 1 en la diagonal
array_identidad = np.identity(3)
array_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Creacion de un ndarray con unos en una de las diagonales

In [14]:
# Cuadrada con unos den la diagonal principal
array_identidad = np.eye(4)
array_identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# Cuadrada con unos en la diagonal especificada
array_con_segunda_diagonal = np.eye(4,k = 1) # Estoy diciendo que vaya a la diagonal 1 por encima de la principal
array_con_segunda_diagonal

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [16]:
# No cuadrada con unos en la diagonal especificada
array_no_cuadrado = np.eye(4, 3, k = -1) # k = -1 le estoy diciendo que vaya a la diagonal -1 por debajo de la principal; ademas indique que quiero que sea de 4x3
array_no_cuadrado

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Creación de un ndarray cuyos elementos son una secuencia numérica

In [4]:
# Dos parámetros: desde el primer valor (incluido) hasta el segundo valor (no incluido)
array_secuencia_2 = np.arange(0, 10)
array_secuencia_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Tres parámetros: desde el primer valor (incluido) hasta el segundo (no incluido) con saltos del tercer valor
array_secuencia_3 = np.arange(5, 20, 2)
array_secuencia_3

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
# Un parámetro: desde 0 (incluido) hasta el valor indicado (no incluido)
array_secuencia_1 = np.arange(10)
print(array_secuencia_1) # Imprime el narray
array_secuencia_1 # Imprime el array con su tipo de dato

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Creación de un ndarray a partir de una secuencia básica de Python

In [10]:
# Unidimensional
array_basico = np.array([1, 2, 3, 4, 5])
print(type(array_basico))
print(array_basico)
print(array_basico[2])

<class 'numpy.ndarray'>
[1 2 3 4 5]
3


In [23]:
# Multidimensional
array_basico_multidimensional = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
array_basico_multidimensional

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Tipos de dato de ndarray de NumPy

- **Enteros con signo:** np.int8, np.int16, np.int32 y np.int64
- **Enteros sin signo:** np.uint8, np.uint16, np.uint32, y np.uint64
- **Numeros en coma flotante:** np.float16, np.float32, np.float64, np.float64 y np.float128
- **Booleanos:** np.bool
- **Objetos:** np.object
- **Cadenas de caracteres:** np.string\_, np.unicode\_
- ...


### Especificacion/Casting/Conversion de tipos entre ndarrays

In [26]:
array_inicial_enteros = np.array([1, 2, 3, 4, 5], np.int32)
print(array_inicial_enteros)
array_inicial_enteros

[1 2 3 4 5]


array([1, 2, 3, 4, 5], dtype=int32)

In [31]:
array_float = np.asarray(array_inicial_enteros, dtype=np.float64)
array_float

array([1., 2., 3., 4., 5.])

In [32]:
array_string = np.array(array_float, dtype=np.unicode_)
array_string

array(['1.0', '2.0', '3.0', '4.0', '5.0'], dtype='<U32')

### Consulta de la composición de un ndarray

<ul>
<li><b>dtype</b>: Tipo del contenido del ndarray.</li>
<li><b>ndim</b>: Número de dimensiones/ejes del ndarray.</li>
<li><b>shape</b>: Estructura/forma del ndarray, es decir, número de elementos en cada uno de los ejes/dimensiones.</li>
<li><b>size</b>: Número total de elementos en el ndarray.</li>
</ul>

In [2]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [3]:
# Tipo de dato (único)
array.dtype

dtype('int64')

In [4]:
# Número de dimensiones
array.ndim

2

In [5]:
# Forma/Dimensiones
array.shape

(3, 4)

In [6]:
# Número total de elementos
array.size

12

### Operaciones aritméticas entre ndarrays y escalares

In [13]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)

In [14]:
# Una de las ventajas de numpy es que, como en este caso, hace todas las operaciones de una vez, no como cuando le sumamos un uno a un array de forma manual en un ciclo
# Suma
array + 5

array([ 6.,  7.,  8.,  9., 10., 11.])

In [15]:
# Resta
array - 2

array([-1.,  0.,  1.,  2.,  3.,  4.])

In [16]:
# Multiplicación
array * 3

array([ 3.,  6.,  9., 12., 15., 18.])

In [17]:
# División
1 / array

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667])

In [18]:
# División entera
array // 2

array([0., 1., 1., 2., 2., 3.])

In [19]:
# Potencia
array ** 2

array([ 1.,  4.,  9., 16., 25., 36.])

In [20]:
# Asignación con operador
array += 1
array

array([2., 3., 4., 5., 6., 7.])

### Operaciones aritméticas entre ndarrays

<b>IMPORTANTE:</b> Los dos términos de la operación tienen que ser ndarrays de las mismas dimensiones y forma. Se aplica la operación elemento a elemento.

In [22]:
array = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)

In [23]:
# Suma (elemento a elmento)
array + array

array([ 2.,  4.,  6.,  8., 10., 12.])

In [24]:
# Resta (elemento a elmento)
array - array

array([0., 0., 0., 0., 0., 0.])

In [25]:
# Multiplicación (elemento a elmento)
array * array

array([ 1.,  4.,  9., 16., 25., 36.])

In [26]:
# División (elemento a elmento)
array / array

array([1., 1., 1., 1., 1., 1.])

In [27]:
# Asignación con operador
array += array
array

array([ 2.,  4.,  6.,  8., 10., 12.])

In [28]:
# Suma de ndarrays de distinto tamaño
array1 = np.array([1, 2,3 ,4, 5])
array + array1

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

### Indexación y slicing básico

En ndarrays unidimensionales el funcionamiento es idéntico al que se tiene en secuencias básicas de Python. Es decir, se utiliza la indexación [a:b:c].

In [29]:
array = np.arange(1, 11)

In [30]:
# Indexación con primer parámetro
array[2]

3

In [31]:
# Indexación con primer y segundo parámetro
array[2:5]

array([3, 4, 5])

In [32]:
# Indexación con tercer parámetro
array[::2]

array([1, 3, 5, 7, 9])

In [33]:
# Indexación con negativos
array[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

<h4>En ndarrays multidimensionales, existen dos posibles formas de realizar el acceso:</h4>
<ul>
<li><b>Mediante indexación recursiva:</b> array[a:b:c en dim_1][a:b:c en dim_2]...[a:b:c en dim_n]</li>
<li><b>Mediante indexación con comas:</b> array[a:b:c en dim_1, a:b:c en dim_2, ...a:b:c en dim_n]</li>
</ul>

In [35]:
array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])
array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [36]:
# Forma de la matriz
array.shape

(2, 2, 4)

In [37]:
# Indexación recursiva primer nivel
array[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
# Indexación recursiva segundo nivel
# Dame la primera matriz pero de esa matriz dame lo que esta en el 0
array[1][0]

array([ 9, 10, 11, 12])

In [39]:
# Indexación recursiva tercer nivel
array[1][0][3]

12

In [40]:
# Indexación con comas segundo nivel
array[1, 0]

array([ 9, 10, 11, 12])

In [41]:
# Indexación con comas tercer nivel
array[1, 0, 3]

12

In [42]:
# Indexación recursiva tercer nivel con slice
array[0][0][:2]

array([1, 2])

In [43]:
# Indexación recursiva tercer nivel con slice de índice negativo
array[1][0][::-1]

array([12, 11, 10,  9])

Del mismo modo a como ocurre en Python básico, se puede utilizar la indexación/slicing para modificar secciones del contenido de un ndarray.

In [44]:
array = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])

In [45]:
# Modificación de una posición
array[0][1] = 50 # La fila 0 al elemento 1 asignale el valor de 50
array

array([[ 1, 50,  3,  4],
       [ 5,  6,  7,  8]])

In [46]:
# Modificación de un slice
# En la fila 0, todos los elementos de dos en dos los vas a cambiar por 30
array[0][::2] = 30
array

array([[30, 50, 30,  4],
       [ 5,  6,  7,  8]])

### Indexación y slicing booleano

In [4]:
personas = np.array(['Miguel', 'Pedro', 'Juan', 'Miguel'])
personas

array(['Miguel', 'Pedro', 'Juan', 'Miguel'], dtype='<U6')

In [5]:
datos = np.random.randn(4, 4)
datos

array([[-1.6972893 ,  0.34795122,  1.40279709, -1.18657977],
       [-1.63862699, -0.17909833, -0.70943232,  0.76615603],
       [-0.23653791, -0.47224386, -0.22939252, -0.07154457],
       [ 0.98058673, -1.21970182, -1.50255882, -0.09292889]])

In [6]:
# Indexación/slicing booleano sobre valores
datos[datos < 0]

array([-1.6972893 , -1.18657977, -1.63862699, -0.17909833, -0.70943232,
       -0.23653791, -0.47224386, -0.22939252, -0.07154457, -1.21970182,
       -1.50255882, -0.09292889])

In [7]:
# Máscara booleana
personas == 'Miguel'

array([ True, False, False,  True])

In [8]:
# Indexación/slicing mediante máscara
datos[personas == 'Miguel']

array([[-1.6972893 ,  0.34795122,  1.40279709, -1.18657977],
       [ 0.98058673, -1.21970182, -1.50255882, -0.09292889]])

In [9]:
# Indexación/slicing mediante máscara y básico combinado
datos[personas == 'Miguel', ::2]

array([[-1.6972893 ,  1.40279709],
       [ 0.98058673, -1.50255882]])

In [10]:
# Indexación/slicing mediante máscara negativo por operador
datos[personas != 'Miguel']

array([[-1.63862699, -0.17909833, -0.70943232,  0.76615603],
       [-0.23653791, -0.47224386, -0.22939252, -0.07154457]])

In [11]:
# Indexación/slicing mediante máscara negativa por signo
datos[~(personas == 'Miguel')]

array([[-1.63862699, -0.17909833, -0.70943232,  0.76615603],
       [-0.23653791, -0.47224386, -0.22939252, -0.07154457]])

De nuevo, podemos utilizar indexación/slicing booleano para realizar modificaciones sobre el contenido de un ndarray.

In [ ]:
array = np.random.randn(7, 4)
array

In [ ]:
# Eliminación de valores negativos mediante slicing
array[array < 0] = 0
array

### Indexación y slicing basado en secuencias de enteros - Fancy indexing

In [3]:
array = np.empty((8, 4)) # Creamos un array (array) y le damos un tamaño de 8 (filas) x 4 (columnas)
for i in range(8): # Para cada elemento hasta 8
    array[i] = i # Para cada fila vamos a ponerle el valor de i
array    

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [4]:
# Indexación/slicing de un conjunto (arbitrario) de elementos
array[[2, 5]] # Aqui selecciono las filas que yo desee

array([[2., 2., 2., 2.],
       [5., 5., 5., 5.]])

In [5]:
# Indexación/slicing de un conjunto (arbitrario) de elementos (índices negativos)
array[[-2, -5]]

array([[6., 6., 6., 6.],
       [3., 3., 3., 3.]])

También podemos indexar de manera arbitraria en múltiples dimensiones, utilizando para ello, una secuencia de enteros por cada dimensión. El resultado será la combinación de secuencias.

In [8]:
array = np.arange(32).reshape((8, 4)) # Creamos un array de tamaño 32 y le cambiamos la forma para que sea de 8 x 4, además 8x4 es 32 por lo que está bien
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [9]:
# Indexación/slicing con una secuencia de varios niveles (elemento a elemento)
array[[1, 5, 7, 2], [0, 3, 1, 2]]
#       Columnas       Filas

array([ 4, 23, 29, 10])

In [10]:
# Indexación/slicing con una secuencia de varios niveles (región resultante)
array[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Trasposición y modificación de ejes/dimensiones

In [11]:
array = np.arange(15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
# Modificación de ejes/dimensiones
array2 = array.reshape(3, 5)
array2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
# Trasposición de ejes/dimensiones"
array2.T # Lo que antes era filas ahora son columnas


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#### Concatenación de ndarrays

Numpy ofrece la posibilidad de combinar ndarrays de dos formas posibles
- **hstack, colum_stack:** Los elementos del segundo array se añaden a lo primero a lo ancho
- **vstack, row_stack:** Los elementos del segundo array se añaden a los primeros del primero

In [18]:
array1 = np.arange(15).reshape(3, 5)
array1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
array2 = np.arange(15, 30).reshape(3, 5)
array2

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [20]:
# Concatenación horizontal (Lo puede hacer porque tiene el mismo numero de filas)
np.hstack((array1, array2))

array([[ 0,  1,  2,  3,  4, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14, 25, 26, 27, 28, 29]])

In [21]:
# Concatenación vertical (Lo puede hacer porque tiene el mismo numero de columnas)
np.vstack((array1, array2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

#### División de ndarrays

Al igual que para la concatenación, NumPy permi9te dividir los ndarray de tres formas distintas:
- **hsplit:** División de arrays en n partes *iguales* por columnas
- **vsplit:** División de arrays en n partes *iguales* por filas
- **split:** División de arrays en n partes no simétricas 

In [22]:
array = np.arange(16).reshape(4, 4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
# División simétrica por columnas
np.hsplit(array, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [24]:
# División simétrica por filas
np.vsplit(array, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [25]:
# División no simétrica. Axis hace el corte por columnas 0 y por filas 1
np.split(array, [1, 3], axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

**Axis**

Valor 0: Aplicará la función por filas


Valor 1: Aplicará la función por columnas

In [26]:
array2.sum(axis=1)

array([ 85, 110, 135])

In [27]:
array2.sum(axis = 0)

array([60, 63, 66, 69, 72])