# Operaciones sobre ndarrays

NumPy pone a nuestra disposición un amplio conjunto de funciones optimizadas para aplicar sobre ndarrays de forma global evitando así la necesidad de utilizar bucles (mucho más costosos).

In [2]:
import numpy as np

### Operaciones elemento a elemento - Universal functions

El primero de los conjuntos de funciones ofrecido por NumPy son las llamadas "funciones universales" (o ufuncs) que permiten la realización de operaciones elemento a elemento de un array. En función del número de parámetros encontramos dos tipos de funciones universales.

#### Funciones unarias

Son aquellas funciones que reciben como parámetro un único ndarray.<br/>
<ul>
<li><b>abs, fabs:</b> Valor absoluto.</li>
<li><b>sqrt:</b> Raíz cuadrada (equivalente a array \*\* 0.5).</li>
<li><b>square:</b> Potencia al cuadrado (equivalente a array ** 2).</li>
<li><b>exp:</b> Potencia de e.</li>
<li><b>log, log10, log2, log1p:</b> Logaritmos en distintas bases.</li>
<li><b>sign:</b> Signo (+ = 1 / - = -1 / 0 = 0).</li>
<li><b>ceil:</b> Techo.</li>
<li><b>floor:</b> Suelo.</li>
<li><b>rint:</b> Redondeo al entero más cercano.</li>
<li><b>modf:</b> Devuelve dos arrays uno con la parte fraccionaria y otro con la parte entera.</li>
<li><b>isnan:</b> Devuelve un array booleano indicando si el valor es NaN o no.</li>
<li><b>isfinite, isinf:</b> Devuelve un array booleano indicando si el valor es finito o infinito.</li>
<li><b>cos, cosh, sin, sinh, tan, tanh:</b> Funciones trigonométricas.</li>
<li><b>arccos, arccosh, arcsin, arcsinh, arctan, arctanh:</b> Funciones trigonométricas inversas.</li>
<li><b>logical_not:</b> Inverso booleano de todos los valores del array (equivalente a ~(array)).</li>
</ul>

In [6]:
array = np.array([1,2,3,4,5])
array[4] = -2
np.abs(array)


array([1, 2, 3, 4, 2])

In [8]:
np.sign(array)

array([ 1,  1,  1,  1, -1])

In [9]:
np.ceil(array)

array([ 1.,  2.,  3.,  4., -2.])

#### Funciones binarias

Son aquellas funciones que reciben como parámetro dos arrays.
<ul>
<li><b>add:</b> Adición de los elementos de los dos arrays (equivalente a array1 + array2).</li>
<li><b>subtract:</b> Resta de los elementos de los dos arrays (equivalente a array1 - array2).</li>
<li><b>multiply:</b> Multiplica los elementos de los dos arrays (equivalente a array1 \* array2).</li>
<li><b>divide, floor_divide:</b> Divide los elementos de los dos arrays (equivalente a array1 / (o //) array2).</li>
<li><b>power:</b> Eleva los elementos del primer array a las potencias del segundo (equivalente a array1 ** array2).</li>
<li><b>maximum, fmax:</b> Calcula el máximo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>minimum, fmin:</b> Calcula el mínimo de los dos arrays (elemento a elemento). fmax ignora NaN.</li>
<li><b>mod:</b> Calcula el resto de la división de los dos arrays (equivalente a array1 % array2).</li>
<li><b>greater, greater_equal, less, less_equal, equal, not_equal:</b> Comparativas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
<li><b>logical_and, logical_or, logical_xor:</b> Operaciones booleanas sobre los elementos de ambos ndarrays (elemento a elemento).</li>
</ul>

In [10]:
array1 = np.random.randn(5, 5) # Definimos un array de 5 x 5 con numeros aleatorios
array1

array([[ 0.63467809, -0.51945379, -1.0393208 , -0.9979384 , -1.03198433],
       [ 2.1452976 , -0.99599057,  2.30894313,  1.01760263,  0.68344513],
       [ 0.7826451 , -0.17434443, -0.31394561, -0.66708367, -1.26382728],
       [ 0.98800971,  0.1630064 , -1.0947669 ,  0.31862895,  0.83862582],
       [ 1.36827095, -1.8467786 , -1.04122472,  0.15828411, -0.33322515]])

In [11]:
array2 = np.random.randn(5, 5) # Definimos un array de 5 x 5 con numeros aleatorios
array2

array([[ 0.1782202 ,  0.63693944, -0.4948465 , -0.80590655, -1.78165539],
       [ 0.61302966,  0.7369971 ,  0.40990245,  0.50621794,  0.39035675],
       [-0.35514359,  0.14404152,  1.27858648, -1.18629857,  2.29057057],
       [-0.15010056, -0.14334323,  0.12844909,  0.05393671, -1.42080642],
       [ 0.21639468, -0.66784138, -1.7108122 ,  0.93590249,  1.82112242]])

In [12]:
np.minimum(array1, array2) # Comparamos posición con posición y ubicamos el menor de ambos valores

array([[ 0.1782202 , -0.51945379, -1.0393208 , -0.9979384 , -1.78165539],
       [ 0.61302966, -0.99599057,  0.40990245,  0.50621794,  0.39035675],
       [-0.35514359, -0.17434443, -0.31394561, -1.18629857, -1.26382728],
       [-0.15010056, -0.14334323, -1.0947669 ,  0.05393671, -1.42080642],
       [ 0.21639468, -1.8467786 , -1.7108122 ,  0.15828411, -0.33322515]])

In [13]:
np.divide(array1,array2) # Divide elemento por elemento

array([[ 3.5612018 , -0.8155466 ,  2.10028928,  1.23828054,  0.5792278 ],
       [ 3.49950048, -1.35141722,  5.63290881,  2.01020655,  1.75082188],
       [-2.2037427 , -1.21037623, -0.24554117,  0.56232359, -0.55175217],
       [-6.58231866, -1.13717545, -8.52296332,  5.90745942, -0.59024636],
       [ 6.32303416,  2.76529523,  0.60861427,  0.16912458, -0.1829779 ]])

In [14]:
np.floor_divide(array1,array2)

array([[ 3., -1.,  2.,  1.,  0.],
       [ 3., -2.,  5.,  2.,  1.],
       [-3., -2., -1.,  0., -1.],
       [-7., -2., -9.,  5., -1.],
       [ 6.,  2.,  0.,  0., -1.]])

### Selección de elementos de ndarrays en función de una condición

NumPy pone a nuestra disposición, a través de la función <b>np.where</b> la posibilidad de generar un array de salida a partir de dos de entrada, estableciendo una máscara booleana que indique si (elemento a elemento) debemos enviar a la salida el elemento del primer ndarray (valor True) o del segundo (valor False).

In [15]:
array1 = np.random.randn(5, 5)
array1

array([[-0.81786984,  0.3036385 , -1.57686781,  0.44762455,  0.91630164],
       [-0.94588856,  0.78716964, -0.07118119, -1.49884434, -1.10136355],
       [-0.96928919,  1.39800906, -0.40319689,  0.85593942,  1.71586952],
       [ 0.70028614,  0.28273004,  1.21840268, -0.33013401,  0.39081097],
       [-1.52625776, -1.09727956, -0.20795991,  0.93037497, -1.51273822]])

In [16]:
array2 = np.random.randn(5, 5)
array2

array([[ 0.54221141,  0.30376515, -1.6468309 , -0.30211424, -0.17029319],
       [-0.06868177,  1.40232435,  1.39652557, -0.22888725, -0.41402323],
       [ 0.46173312,  0.90351042, -0.3454628 ,  0.99022318, -1.83777598],
       [-0.3846442 , -1.30723239,  0.7331737 , -1.68439226,  1.84295914],
       [-0.42376579, -2.46594545,  0.40301302,  1.52498456,  1.26659869]])

In [17]:
# Fusión condicional
np.where(array1 < array2, array1, array2) # Si array1 es menor a array2 (para cada elemento), devuelve array1 y si no, array2

array([[-0.81786984,  0.3036385 , -1.6468309 , -0.30211424, -0.17029319],
       [-0.94588856,  0.78716964, -0.07118119, -1.49884434, -1.10136355],
       [-0.96928919,  0.90351042, -0.40319689,  0.85593942, -1.83777598],
       [-0.3846442 , -1.30723239,  0.7331737 , -1.68439226,  0.39081097],
       [-1.52625776, -2.46594545, -0.20795991,  0.93037497, -1.51273822]])

In [ ]:
# Anidación de condiciones
np.where(array1 < array2, np.where(array1 < 0, 0, array1), array2) # Si array1 es menor que array2 ejecuto el where y si no devuelvo array2

### Funciones matemáticas y estadísticas

NumPy ofrece un amplio conjunto de funciones matemáticas y estadísticas que se pueden aplicar sobre ndarrays. A continuación se pueden encontrar los ejemplos más típicos (hay algunas más que pueden consultarse en la documentación oficial de NumPy).<br/>
<ul>
<li><b>sum:</b> Suma de elementos.</li>
<li><b>mean:</b> Media aritmética de los elementos.</li>
<li><b>median:</b> Mediana de los elementos.</li>
<li><b>std:</b> Desviación estándar de los elementos.</li>
<li><b>var:</b> Varianza de los elementos.</li>
<li><b>min:</b> Valor mínimo de los elementos.</li>
<li><b>max:</b> Valor máximo de los elementos.</li>
<li><b>argmin:</b> Índice del valor mínimo.</li>
<li><b>argmax:</b> Índice del valor máximo.</li>
<li><b>cumsum:</b> Suma acumulada de los elementos.</li>
<li><b>cumprod:</b> Producto acumulado de los elementos.</li>
</ul>

Todas estas funciones pueden recibir, además del ndarray sobre el que se aplicarán, un segundo parámetro llamado <b>axis</b>. Si no se recibe este parámetro las funciones se aplicarán sobre el conjunto global de los elementos del ndarray, pero si se incluye, podrá tomar dos valores:
<ul>
<li>Valor 0: Aplicará la función por filas</li>
<li>Valor 1: Aplicará la función por columnas</li>

In [18]:
array = np.random.randn(5, 4)
array

array([[ 0.84109111,  0.90642692, -0.6516805 ,  0.77752794],
       [-0.47675354,  1.31899386,  1.33289445, -1.35745677],
       [ 0.9939185 , -1.01421652,  1.2512057 ,  0.35256253],
       [ 0.45986738, -2.31630514,  1.00646852,  0.00546988],
       [ 0.68661106, -0.71520978,  0.8930337 , -0.61162511]])

In [19]:
# Operación global
np.sum(array)

3.682824186552079

In [20]:
# Operación por filas
np.sum(array, axis=0)

array([ 2.50473451, -1.82031065,  3.83192186, -0.83352153])

In [21]:
# Operación por columnas
np.sum(array, axis=1)

array([ 1.87336546,  0.817678  ,  1.58347022, -0.84449935,  0.25280987])

Adicionalmente algunas de estas funciones pueden ser utilizadas como "métodos" de los ndarray y no sólo como funciones sobre los mismos. En este caso la sintáxis cambiará y se utilizará la notación "ndarray.funcion()" 

In [22]:
array.sum()

3.682824186552079

In [23]:
np.argmax(array) # El valor máximo de la matriz

6

In [24]:
np.argmin(array) # El valor minimo

13

In [25]:
np.cumsum(array) # Suma acumulada: va sumando uno por uno 

array([0.84109111, 1.74751803, 1.09583752, 1.87336546, 1.39661191,
       2.71560577, 4.04850022, 2.69104345, 3.68496196, 2.67074544,
       3.92195114, 4.27451367, 4.73438106, 2.41807592, 3.42454444,
       3.43001432, 4.11662538, 3.4014156 , 4.2944493 , 3.68282419])

In [26]:
np.cumprod(array) #Producto acumulado: multiplando uno por uno

array([ 8.41091107e-01,  7.62387620e-01, -4.96833149e-01, -3.86301653e-01,
        1.84170682e-01,  2.42919999e-01,  3.23786718e-01, -4.39526471e-01,
       -4.36853491e-01,  4.43064025e-01,  5.54364234e-01,  1.95448058e-01,
        8.98801871e-02, -2.08189939e-01, -2.09536620e-01, -1.14614034e-03,
       -7.86952634e-04,  5.62836216e-04,  5.02631708e-04, -3.07422176e-04])

### Operaciones sobre ndarrays booleanos

Dado que, internamente, Python trata los valores **booleanos True como 1 y los False como 0**, es muy sencillo realizar operaciones matemáticas sobre estos valores booleanos de forma que se puedan hacer diferentes chequeos. Por ejemplo...

In [27]:
array = np.random.randn(5, 5)
array

array([[-0.33435502,  0.14756562, -0.41918774,  0.02912785,  0.66324544],
       [ 0.90886548,  0.7199409 , -1.41486851,  0.3676829 , -0.23657398],
       [-2.43587102, -0.60141112, -0.07412603, -0.02188068, -2.08821499],
       [ 0.57000251,  0.70233952, -0.24960456,  0.50812711, -1.15282625],
       [ 0.54330409,  1.76444439, -0.53282576, -1.61824666, -1.35881261]])

In [28]:
# Elementos mayores que 0
(array > 0).sum() # Elementos del array que son mayores que cero (osea true, osea 1) y suma esos 1.

11

In [29]:
# Elementos menores que la media
(array < array.mean()).sum() 

12

NumPy también pone a nuestra disposición dos funciones de chequeo predefinidas sobre ndarrays booleanos:<br/>
<ul>
<li><b>any:</b> Para comprobar si alguno de los elementos es True.</li>
<li><b>all:</b> Para comprobar si todos los elementos son True.</li>
</ul>

In [30]:
# Alguno de los elementos cumple la condición
(array == 0).any() # Hay algún elemento que sea cero ?

False

In [31]:
# Todos los elementos cumplen la condición
((array >= -2) & (array <= 2)).all()

False

### Ordenación de ndarrays

In [32]:
array = np.random.randn(5, 5)
array

array([[ 0.65104624,  0.31104594, -0.5107855 , -0.76997821,  0.43196525],
       [-0.13179057,  0.07120656,  1.0470553 , -0.31089086,  1.09946947],
       [-2.48095449,  1.33979543,  1.82202267,  1.15620711, -0.4438632 ],
       [ 0.58634838, -1.11823195,  1.72040791, -0.39133681, -0.39659994],
       [-0.33186127, -0.90600009, -0.49529023,  0.09637086, -0.34855968]])

In [33]:
# Datos ordenados
np.sort(array) # Está ordenando por fila

array([[-0.76997821, -0.5107855 ,  0.31104594,  0.43196525,  0.65104624],
       [-0.31089086, -0.13179057,  0.07120656,  1.0470553 ,  1.09946947],
       [-2.48095449, -0.4438632 ,  1.15620711,  1.33979543,  1.82202267],
       [-1.11823195, -0.39659994, -0.39133681,  0.58634838,  1.72040791],
       [-0.90600009, -0.49529023, -0.34855968, -0.33186127,  0.09637086]])

In [34]:
# Datos ordenados según el primer eje
np.sort(array, axis=0)

array([[-2.48095449, -1.11823195, -0.5107855 , -0.76997821, -0.4438632 ],
       [-0.33186127, -0.90600009, -0.49529023, -0.39133681, -0.39659994],
       [-0.13179057,  0.07120656,  1.0470553 , -0.31089086, -0.34855968],
       [ 0.58634838,  0.31104594,  1.72040791,  0.09637086,  0.43196525],
       [ 0.65104624,  1.33979543,  1.82202267,  1.15620711,  1.09946947]])

### Funciones de conjunto

NumPy permite realizar tratamientos sobre un ndarray asumiendo que el total de los elementos del mismo forman un conjunto.<br/>
<ul>
<li><b>unique:</b> Calcula el conjunto único de elementos sin duplicados.</li>
<li><b>intersect1d:</b> Calcula la intersección de los elementos de dos arrays.</li>
<li><b>union1d:</b> Calcula la unión de los elementos de dos arays.</li>
<li><b>in1d:</b> Calcula un array booleano que indica si cada elemento del primer array está contenido en el segundo.</li>
<li><b>setdiff1d:</b> Calcula la diferencia entre ambos conjuntos.</li>
<li><b>setxor1d:</b> Calcula la diferencia simétrica entre ambos conjuntos.</li>
</ul>

In [35]:
array1 = np.array([6, 0, 0, 0, 3, 2, 5, 6])
array1

array([6, 0, 0, 0, 3, 2, 5, 6])

In [36]:
array2 = np.array([7, 4, 3, 1, 2, 6, 5])
array2

array([7, 4, 3, 1, 2, 6, 5])

In [37]:
np.unique(array1)

array([0, 2, 3, 5, 6])

In [38]:
np.union1d(array1, array2)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
np.in1d(array1, array2)

array([ True, False, False, False,  True,  True,  True,  True])